import java.util.Scanner;
import java.io.FileInputStream;
import java.io.IOException;

/**
 * Application to demonstrate the use of a stack by simulating an editor's un/redo operations.
 *
 * DO NOT EDIT THIS FILE!
 * 
 * @author lynda, rt
 */
public class UndoRedo {
     
    private static Stack doneStack;
    private static Stack undoneStack;
    
    public static void initArrayStacks() {
        doneStack = new ICS124Stack1();
        undoneStack = new ICS124Stack1();
    }
    
    public static Scanner openFile(String fileName) throws IOException{
        Scanner fileStream;
        FileInputStream fileByteStream = new FileInputStream(fileName);
        return(new Scanner(fileByteStream));
    }
    
    public static void performOperation(String operation) {
        System.out.println("\n- Performing Operation: " + operation + " started.");
        switch (operation) {
            case "typing" :
            case "auto format" :
            case "bold" :
            case "italic" :
            case "copy text" :
                doneStack.push(operation);
                break;
            
            case "UNDO" :
                if (doneStack.isEmpty())
                    System.out.println("x Cannot undo. Nothing to undo.");
                else {
                    operation = (String) doneStack.pop();
                    undoneStack.push(operation);
                }
                break;
                
            case "REDO" :
                if (undoneStack.isEmpty())
                    System.out.println("x Cannot redo. Nothing to redo.");
                else {
                    operation = (String) undoneStack.pop();
                    doneStack.push(operation);
                }
                break;
        }
        System.out.println("Operation: " + operation + " completed.");
    }
    
    
    /* This program performs operations in the order given in a supplied input file.
    * The operations are repeated for both ArrayStack and LinkedStack implementations. Both
    * tests should produce identical output.
    */
    public static void main(String[] args) throws Exception {
        String fileName;
        Scanner inputFileStream;
        String operation;
        
        Scanner keyboard = new Scanner(System.in);
        System.out.print("Enter file name: ");
        String filename = keyboard.nextLine();

        // Begin test.
        System.out.println("--- Beginning Test ---");
        initArrayStacks();
        inputFileStream = openFile(filename);
        
        while (inputFileStream.hasNextLine()) {
            operation = inputFileStream.nextLine();
            performOperation(operation);
        }
        System.out.println();
        inputFileStream.close();
		
		   // Test for -ve growthIncrement
		   Stack testStack = new ICS124Stack1(10, -1);
   }
}
